name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    container: devkitpro/devkitarm:latest

    steps:
      - uses: actions/checkout@v2

      - name: Fix apt sources
        run: |
          apt-get update
          apt-get -y install dirmngr
          echo 'deb http://us.archive.ubuntu.com/ubuntu/ bionic main' >> /etc/apt/sources.list
          apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
          apt-get update

      - name: Install and update packages
        run: |
          apt-get -y install python3 python3-pip p7zip-full libarchive13 git
          python3 --version
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install cryptography
          python3 -m pip install git+https://github.com/TuxSH/firmtool.git
          
      - name: Where tf am I
        run: |
          pwd
          ls -la
          git status

      - name: Build Project
        run: make release
